#index:
#    path: /
#    controller: App\Controller\DefaultController::index


app_home:
    path: /
    controller: App\Controller\HomeController::index

services_show:
    path: /services/{name}
    controller: App\Controller\ServiceController::showService

auth_show:
    path: /show/{name}
    controller: App\Controller\AuthorController::showAuthor